import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { downloadArtifact } from "../../api/validationRuns";
import { SEVERITY_LABEL, STEP_STATUS_LABEL, } from "./validationFormat";
export function StepResultCard({ step }) {
    const [open, setOpen] = useState(false);
    const findings = step.findings_json ?? [];
    return (_jsxs("div", { className: "step-card", children: [_jsxs("button", { type: "button", className: "step-card-header", onClick: () => setOpen((v) => !v), "aria-expanded": open, children: [_jsx("span", { className: "step-card-caret", "aria-hidden": true, children: open ? "▾" : "▸" }), _jsx("span", { className: "step-card-title", children: step.display_name || step.step_name }), _jsx("span", { className: `val-badge val-status-${step.status}`, children: STEP_STATUS_LABEL[step.status] }), step.severity !== "none" && (_jsx("span", { className: `val-badge val-sev-${step.severity}`, children: SEVERITY_LABEL[step.severity] }))] }), open && (_jsxs("div", { className: "step-card-body", children: [step.summary && _jsx("p", { style: { marginTop: 0 }, children: step.summary }), step.error_message && (_jsx("pre", { className: "error", style: { whiteSpace: "pre-wrap" }, children: step.error_message })), findings.length > 0 && (_jsxs("table", { className: "data findings-table", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { style: { width: 90 }, children: "Severity" }), _jsx("th", { children: "Finding" }), _jsx("th", { children: "Resource" })] }) }), _jsx("tbody", { children: findings.map((f, i) => (_jsxs("tr", { children: [_jsx("td", { children: _jsx("span", { className: `val-badge val-sev-${f.severity}`, children: SEVERITY_LABEL[f.severity] }) }), _jsxs("td", { children: [_jsx("strong", { children: f.title }), f.message && (_jsx("div", { className: "muted", style: { fontSize: 13 }, children: f.message })), f.recommendation && (_jsxs("div", { style: { fontSize: 12, marginTop: 2 }, children: ["\u21B3 ", f.recommendation] }))] }), _jsx("td", { children: _jsx("code", { style: { fontSize: 12 }, children: f.resource ?? "—" }) })] }, i))) })] })), _jsx("div", { className: "step-card-meta muted", children: step.completed_at && (_jsxs("span", { children: ["Completed ", new Date(step.completed_at).toLocaleString()] })) }), step.artifacts.length > 0 && (_jsxs("div", { className: "step-artifacts", children: [_jsx("span", { className: "muted", style: { fontSize: 12 }, children: "Evidence:" }), step.artifacts.map((a) => (_jsxs("button", { type: "button", className: "artifact-link", onClick: () => downloadArtifact(a), title: `${a.artifact_type} · ${a.size_bytes} bytes`, children: ["\u2B07 ", a.artifact_name] }, a.id)))] }))] }))] }));
}
